### ISSUE TITLE
ATtiny85 TX pin dependend on clockspeed

### ISSUE THREAD

**Issue by qistoph** [jscrane/TinyDebugSerial#1]
Is it intentional to used a different TX pin for the ATtiny when it runs on more than 8MHz?
What would be the motivation for that?

[Line 610-612](https://github.com/jscrane/TinyDebugSerial/blob/master/TinyDebugSerial.h#L610) vs [Line 614-616](https://github.com/jscrane/TinyDebugSerial/blob/master/TinyDebugSerial.h#L614)

````
607 #elif defined( __AVR_ATtiny85__ )
608 
609   #if F_CPU <= 8000000L
610     // port B bit 3 (PB3)
611     #define TINY_DEBUG_SERIAL_REGISTER    0x18
612     #define TINY_DEBUG_SERIAL_BIT         3
613   #else
614     // port B bit 2 (PB2)
615     #define TINY_DEBUG_SERIAL_REGISTER    0x18
616     #define TINY_DEBUG_SERIAL_BIT         2
617   #endif
618
619 #endif
````

**Comment by qistoph** [comment]
Dear @jscrane,

Could you please have a look at this issue and the pending PR?

**Comment by jscrane** [comment]
Note that this is not my original code. See the README.

The best explanation for this code that I can come up with is that PB3 is also known as XTAL1. See [here](https://camo.githubusercontent.com/081b569122da2244ff7de8bae15eb56947d05cc8/687474703a2f2f6472617a7a792e636f6d2f652f696d672f50696e6f7574543835612e6a7067).

This means when the CPU speed is <= 8MHz, you're using the internal oscillator for the clock and can therefore use PB3 for output. If the CPU speed is greater, you have to attach a crystal and you can't use PB3.

Hope this is clear, and makes it clear why I will decline your PR. Thanks anyway!
